[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc-version = "0.8.4"
evm_version = 'london'
gas_reports = ['*']
remappings = ['@rari-capital/solmate/=node_modules/@rari-capital/solmate/',
'forge-std/=lib/forge-std/src/',
'hardhat/=node_modules/hardhat/',
'hardhat-deploy/=node_modules/hardhat-deploy/'
]
chain_id = 1
# force = true
gas_limit = 9223372036854775807                              
gas_price = 0


[fuzz]
# We reduce the number of fuzz runs for now.
runs = 100

[profile.default.fmt]
line_length=80
tab_width=4
bracket_spacing=false
quote_style='double'
number_underscore='thousands'
# NOTE may change later.
func_attrs_with_params_multiline=true

# See more config options https://github.com/gakonst/foundry/tree/master/config
